alcatraz/alcatraz-packages

- packages.json
In Xcode 6 and onwards, the Empty Application template has been removed. But you can add it back manually. This repo is to automate the process.
> Added Empty Application template details.

- packages.json
Existing should still work fine with redirects for the next couple months, but I'd like to make this official.
> Update org name/urls for XcodeAutoBasher

- packages.json
Project URL contains the README page which has to the setup and usage notes, necessary for first time users of the plugin.
> Updating description to have project URL

- packages.json
Hello!
Adding this plugin that that helps to show gcov data over the text editor in XCode. Let me know if you have any problems.
Thanks!
Tyler
> Adding XCoverage plugin to Alcatraz

- packages.json
This adds the SimpleXcodeIcon plugin-in I wrote to the package specs.
> Add SimpleXcodeIcon plug-in

- packages.json
Just noticed that someone submitted my theme, unfortunately with broken link. Fixed with some metadata facelift.
> Metadata fix for eppz! color theme (by original author)

- packages.json
Hi, this plugin help user export their .sketch assets to Images.xcassets. But it is depend on cli sketchtool.
> Submit for SketchExporter

- packages.json
The Plugin is used to symbolicate crashes. If `dSYM` file and `crash` file is available, the crash can be symbolicated using the Plugin.
> Plugin to symbolicate crashes and fetch details of the application binary.

- packages.json
This is a file template plugin that allows selecting an open source license to appear in the header of a Swift file.
> Added reference to LicensedSwiftTemplates file template repo.

- packages.json
Remove the plugin OCMiniXcode.
The plugin is un-buildable as-is because the xcodeproj is named `OCMiniXcode.xcodeproj` and the plugin is named `MiniXcode`.
Also, the plugin isn't compatible with any newer version of Xcode since 5.1 and wasn't updated in a year.
> Remove MiniXcode

- packages.json
This Xcode Plugin Will Identify the untrashed Files in Currently opened Project. And Display the list of Path in Xcode console. Thanks to KFCocoaPodsPlugin for Console Logs. To use this Goto Edit/Identify Unused Files. Now Xcode Console Print the UnTrashes files from Your Current Project.
> Added UnTrashed-Files Plugin

- packages.json
Added a new package to directly open the locations of files and projects in iTerm. This uses Terminal app as a backup option if iTerm is not installed.
> Added Spec for Open in iTerm plugin

- packages.json
I had a custom, more appropriate name but now I'm changing it to the name of the project (not bothering to rename all the appropriate files). Is it required to have the exact same name? If not, please close this PR for me. Thanks
> Renaming package to name of .xcodeproj file

- packages.json
Having ConfigurableVariable set as name, and ConfigurableVariable.xcworkspace at the root of the git repo doesn't seem to work, project is recognized as a template. Changed all names to match the repo name: SYConfigurableVariable
> Fixed SYConfigurableVariable name

- packages.json
Recently, OFPlugin became OFXcodeMenu and switched repositories to be hosted by the @openframeworks organization.
Alcatraz doesn't seem to be handling the redirect to the new location automatically, so this adds the correct (new) location and screenshot, etc.
@admsyn - in response to https://github.com/openframeworks/OFXcodeMenu/issues/40
> Update OFPlugin to OFXcodeMenu and location

- packages.json
Added my Xcode theme, [Prism](https://github.com/xcorlett/prismtheme-xcode). Prism tries to emulate the default color scheme from Lea Verou's excellent [prism.js](http://prismjs.com) syntax highlighter.
> Update packages.json: New Theme (Prism)

- packages.json
CedarShortcuts is an Xcode plugin that adds handy shortcuts for Cedar or Quick.
For example: Cedar and Quick allow you to focus on examples with fit/fdescribe but with this plugin you can select it/describe with your cursor and use a shortcut instead.
> Add CedarShortcuts to package.

- packages.json
Sorry for this.
Original screenshot is too large, 2796 x 1746.  Made by retina screen, 
Looks like,
It's too ugly. Now change to 600x376. 
https://cloud.githubusercontent.com/assets/5022872/10865607/a840173e-804b-11e5-93a4-a054743951a7.jpg
Forgive me...
@jurre
> update screenshot in Reveal-In-Github plugin

- packages.json
After installing this plugin, no rect will contain half pixels. This is useful *only* when using autolayout to prevent Xcode anarchy (it modifies +- 0.5px according to screen scale).
> Add IBUnfuck as a package

- packages.json
Sorry for that, some people say my spelling Github is wrong, so I change to GitHub in my project. Change `https://github.com/lzwjava/Reveal-In-Github` to `https://github.com/lzwjava/Reveal-In-GitHub`, and xcodeproj name, etc.
But installing by alcatraz will fail. Say,
> Wasn't able to find: Reveal-In-Github.xcodeproj in /**************/Library/Application Support/Alcatraz/Plug-ins/Reveal-In-Github
in [this issue](https://github.com/lzwjava/Reveal-In-GitHub/issues/4).
So I change the plugin name and url in the packages.json to fix it.
@jurre
> rename Github to GitHub In Reveal-In-GitHub plugin

- packages.json
Adds the following plugin: https://github.com/alloy/LLDB-Is-It-Not
> Add ‘LLDB, Is It Not?’ Xcode plugin.

- packages.json
The script used to check for the urls was:
```
packages=$(curl --location --silent "https://raw.github.com/alcatraz/alcatraz-packages/master/packages.json")
urls=$(echo "${packages}" | grep '"screenshot":' | awk '{ print $2 }' | sed s/\"//g | sed s/,//g)
for url in ${urls}; do
result=$(curl-check-url "${url}") && echo -n "." || echo -e "\n${url} FAILED with ${result}"
done
```
This depends on `brew install tsparber/tiny-scripts/curl-check-url`.
> Fix 404 urls (screenshots, dead projects)

- packages.json
Adding **Phoenix** - a plugin that turns a selected list of properties into a dependency injected initializer and copies it to your pasteboard. For Objective-C and Swift.
1. Select your properties
2. Go to `Edit` and then click `Make Initializer And Copy` OR use the key command CMD - Shift - X.
3. Paste your initializer wherever you wish
Let me know if I set something up wrong or there are any other issues, thank you!
> Adding Phoenix

- packages.json
I threw together a solution to a long-frustrating problem I had with Xcode & light-on-dark fonts: https://github.com/liscio/ThinStrokes.
`rspec` passed, and I have a release tag + binary up as well. Let me know if I missed anything!
> Adding ThinStrokes to the list

- packages.json
I want to add my plugin( https://github.com/manji602/ImportSorter ) onto alcatraz.
This plugin enables to sort import declarations on Xcode, like show in below:
> add ImportSorter

- packages.json
A Xcode plugin which calls http://tinypng.com api to minimize image assets
> add RTTinyPNGWebAPIPlugin

- packages.json
Add plugin that automatically makes `@IBOutlets` Optional when generated through IB.
> Add OptionalOutlets

- packages.json
AMLocalizedStringBuilder is the localized string helper which help you build your "Localizable.strings" file to class with shortcut ctrl+f.
> Added AMLocalizedStringBuilder-Xcode-Plugin.

- packages.json
The current screenshot wasn't looking ok.
New screenshot:
> Updates Swiftr thumbnail to better fit the package manager's layout

- packages.json
Add "Restart RestartSourceKitService!" to Xcode Debug menu. Sometimes highlighting for Swift is not working and can't be recovered itself...
> Add Plugin RestartSourceKitService

- packages.json
Updating the link as it's no longer working.
The original link with the spaces (%20) has been changed to underscore (_).
> Update Solarized Dark for Xcode link and description

- packages.json
It has Atom and Sublime support already, I'll be sending a PR mentioning Alcatraz support [on the site](http://sailorhg.github.io/fairyfloss/) once this is merged.
> Adds Fairyfloss theme.

- packages.json
Adding package iTimeTrack, which is a fork of wakatime but logs heartbeats to the itimetrack.com website and automatically generates billable time entries.
> Add iTimeTrack plugin take 2

- packages.json
The plugin depends on Cocoapods, so installation is guaranteed to fail.
Moreover, the plugin hasn't been updated since 2014, and is only compatible with Xcode 5.
Full build log: https://gist.github.com/guillaume-algis/35b8df1dc49cb7f1480cfe2294a18e43
> Remove plugin BTGisterPost-Xcode5

- packages.json
move HQBlockMention to plugin part,why not split the json file into 4 different file?
> move HQBlockMention to plugin part

- packages.json
Hello again and sorry for this PR.
I didn't read that the name of the project must match with the name in the packages.json
Thanks in Advance
> Rename Auto Select targets to AutoSelectTargets

- packages.json
Ran a script to check all screenshot URLs, and fixed/removed all the invalid ones.
Specifically:
- ~~Quick Templates: HTTP 403 | ping @modocache~~
- Xcode-Coordinator-Template: Link to github page
- Blacktea theme: Link to github page
- OCPropertyTransfer: Link to github page
- ProjectCleaner: Link to github page
- LCJSONFormatter: Link to github page
- QCBlockCommenter: Link to github page
- ~~xTransCodelation: HTTP 404 | ping @AsTryE~~ Fixed #623 
- XActivatePowerMode: HTTP 404 | ping @qfish
- XcodePerforcePlugin: HTTP 404 | ping @AhiyaHiya 
- HQBlockMention: Link to github page
The "Link to github page" errors were fixed, URLs returning a HTTP error were removed.
Full report [here](https://gist.github.com/guillaumealgis/bfa356c58fa769279ee348bc5e465979)
> Fix broken screenshots URLs

- packages.json
I will soon replace the master branch with a standalone OSX app (due to lack of plug-in support in Xcode 8). This will in other words soon stop working here.
> Removed build time analyzer
