packages.json
For end-to-end testing and generally not having to pick up your device.
=> New Plugin “Remote"

packages.json
=> Updated Peckham screenshot

packages.json
https://github.com/hanton/CopyIssue-Xcode-Plugin
=> Add HTYCopyIssue

packages.json
new package for Swift File Templates
=> Swift File Templates

packages.json
@jurre like this, or do I have to merge to master ah
gain, after `git rebase -i` ?
=> Adding LinkedLog

packages.json
Hi guys,
Its my first plugin.
Waiting for your reply.
thanks.
=> add KSHObjcUML plugin

packages.json
Admittedly this is only really useful for a subset of folks using a specific method of localization, but if you wouldn't mind adding this alcatraz I would greatly appreciate it. Thanks!
=> Added URBNLin Plugin.

packages.json
=> Add chroma light colorscheme

packages.json
I'm the owner of BBUncrustifyPlugin. I have updated the description and added a screenshot.
=> Added a screenshot and changed the description of BBUncrustifyPlugin

packages.json
Requesting for XCActionBar publishing.
=> Submitting XCActionBar plugin package spec

packages.json
=> add AxeMode plugin by @alloy

packages.json
Add plugin HighlightSelectedString
=> Add plugin HighlightSelectedString

packages.json
Added iOS project templates to replace the missing Empty Application template.
=> Added MMJiOSTemplates

packages.json
Updated URL for XcodePerforcePlugin project since it has changed on the host.
=> Updated URL for XcodePerforcePlugin project.

packages.json
Prior URL had to be updated to correct path.
=> Updated screenshot url for perforce plugin.

packages.json
Xcode plugin that makes working with CAMediaTimingFunction more visual.
=> Add CATweakerSense Plugin

packages.json
Xcode plugin that move the instruction pointer to the selected line.
=> Added SFJumpToLine plugin

packages.json
Hey adding a new file template, for [OpenFrameworks](http://openframeworks.cc/) classes.
Thx so much for doing this btw! Really useful!
=> add OpenFrameworks file templates

packages.json
Added Specials Board to color themes section and ran rspec which passed:
```sh
$ rspec
.......
Finished in 0.02856 seconds
7 examples, 0 failures
```
=> Added Specials Board to color theme section

packages.json
You can quickly enter the iOS simulator Xcode plugin!
=> Add ZLGotoSandboxPlugin Plugin

packages.json
Hey ,
This is redundant files a lookup project (not the referenced file). Xcode - plugin.
- Thx
=> Add ZLCheckFilePlguin

packages.json
Add ZLXCodeLine Plugin. This is a record of the number of lines of code - Xcode
=> Add ZLXCodeLine Plugin

packages.json
Plugin, helping to spot if you're currently working in the beta Xcode.
=> BetaWarpaint

packages.json
changed ownership to Adorkable
=> Seguecode plugin

packages.json
Made a plugin for making an app icon from Xcode, without using any 3rd party apps or online services.
=> adds IconMaker to packages

packages.json
My first github pull request. HAPPY! Please review my plugin and merge it, thanks.
=> add XcodeMediaLibraryTweak

packages.json
A colorful and vibrant Xcode theme, ported from the excellent [Oceanic Next Theme](https://github.com/voronianski/oceanic-next-theme).
=> Add Oceanic Next theme

packages.json
sorry, XcodeMediaLibraryTweak screenshot key fix
=> fix XcodeMediaLibraryTweak screenshot

packages.json
=> add  SwiftCodeSnippets

packages.json
Simple templates for *Mantle*.
=> Add Mantle templates

packages.json
Added SCXcodeEditorInset and updated descriptions and screenshots for SCXcodeMinimap and SCXcodeSwitchExpander
=> Added SCXcodeEditorInset

packages.json
- https://github.com/knutigro/Xcode-Plugin-Application-Support
=> Application Support Folder

packages.json
I added my plugin ColorSenseRainbow and the second change was modifying a typo that I made in the first.
=> Adding plugin ColorSenseRainbow

packages.json
CoPilot is a plugin for collaborative editing. See http://feinstruktur.com/copilot/ for more details.
I'm unsure how to fully test that building the plugin via Alcatraz is working. It's using a fair number of submodules but builds fine for me across three different machines. Please let me know if there's something I can do to test this.
=> Added CoPilot plugin

packages.json
I hope I get it right this time.
Repo URL : `https://github.com/kittinunf/RealmBrowser-Plugin`
Xcodeproj name : `RealmBrowser.xcodeproj`
=> Add RealmBrowser-Plugin to Alcatraz

packages.json
I hope I get it right this time.
Repo URL : https://github.com/EnjoySR/ESJsonFormat
Xcodeproj name : ESJsonFormat.xcodeproj
=> Add plugin ESJsonFormat to Alcatraz

packages.json
I've added a DOS inspired theme for Xcode.
Including 2 different themes.
=> Added a retro DOS theme

packages.json
=> Added XCSnippetr plugin – Slack and Gist uploader

packages.json
Request to add the JumpMarks plugin as described here: https://github.com/merrickp/JumpMarks
=> Add JumpMarks plugin

packages.json
https://github.com/chroman/XReset
=> Add XReset Xcode Plugin

packages.json
I 😍 `Dusk`.
Who doesn't !?
But it would be even better if it had a presentation alternative, so we wouldn't have to use the default theme on Xcode.
=> Adds Dusk Presentation themes

packages.json
Spec template for https://github.com/pivotal/cedar
=> Add a file template entry for Cedar BDD

packages.json
=> SilentNight Theme

packages.json
Add DCLazyInstantiate Xcode plugin.
=> Add DCLazyInstantiate Xcode plugin.

packages.json
=> Added Distraction Free Plugin

packages.json
https://github.com/robertvojta/LigatureXcodePlugin/releases/tag/v1.0
=> Ligature Xcode plug-in

packages.json
https://github.com/boyXiong/XWJsonToCode
description:
Adding a plug-in to the Objective-C language code generated by the Json format data
=> Add Xcode plugin

packages.json
=> Fixed SYConfigurableVariable listed as template

packages.json
Bookmark features like Toggle/Next/Prev Bookmark,Show Bookmarks.
=> add plugin XBookmark

packages.json
> A plug-in for Swift projects, which adds calls to `super` in certains methods like `viewDidLoad` etc.
=> Add SuperFixer plugin

packages.json
First pull request for DOSNewLine
=> DOSNewLine plug-in added.

packages.json
Add HHEnumeration-Xcode plugin
=> Add HHEnumeration-Xcode plugin

packages.json
First time doing this, hopefully it’s right! ^_^
=> Add Multiplex plugin

packages.json
Hope to be powered by Alcatraz. Thanks.
@jurre
=> Add Reveal-In-Github plugin

packages.json
The screenshot changed from a png to a gif.
=> Updated screenshot for KSImageNamed.

packages.json
add swimat plugin: swift code formatter
=> add swimat(swift formatter) plugin

packages.json
=> Adds You Can Do It

packages.json
Added a https://github.com/zats/PreciseCoverage Xcode plugin
=> PreciseCoverage

packages.json
Fixed JSON format error #line125
=> Added XActivatePowerMode.

packages.json
Change the font of XCode Navigator Area. For someone who like everything in monospace.
=> MMNavigatorFont

packages.json
Added my new plugin to alcatraz spec
=> Add KZLinkedConsole plugin

packages.json
Please merge this, ASAP.  Thanks!
=> DVTPlugInCompatibilityUUIDifier (new plugin)

packages.json
a plugin for time convert from 1970
=> add Time1970Convertor plugin

packages.json
=> add SwiftJsonToObj plugin

packages.json
This has stopped alcatraz from working!
=> Fix broken JSON syntax

packages.json
=> Back to original name

packages.json
=> Update packages.json to add VWInstantRun plugin

packages.json
My first Xcode-plugin. Hope, everything is OK.
=> ExtComments added

packages.json
A Xcode Plugin to quick show in finder with using shortcut key（alt+f）.
=> Add QuickShowInFinder Plugin

packages.json
=> Add FKConsole plugin

packages.json
I hope my theme will be loved by people as much as I do
=> Added Aytharn colour theme

packages.json
Sorry, I did omit the raw. version of the screenshot!
Here's the fix
=> fixed wrong link to Aytharn's screenshot

packages.json
Added, Xcode template to generate swift theme manager.
=> DRL-Theme-Manager added

packages.json
This plugins is for managing all the strings in iOS developing. And it support both object-c and swift projects. I will support it after it has been released on Package manager. Please review it and tell me the disadvantages. Thanks.
=> A Xcode plugin for managing strings in your projects

packages.json
The screenshot will not show on Package Manager before. I have changed it to raw image url. Please check it. Thanks.
=> Change the screenshot of StringManage to raw data

packages.json
Added NSOperationTestCaseTemplate file template
=> Added NSOperationTestCaseTemplate at line 1908

packages.json
Added new plugin SYXcodeIconVersion :)
=> Added SYXcodeIconVersion

packages.json
=> Add FKRealGroup

packages.json
Added entry for xSendIssue plugin.
=> Added xSendIssue plugin entry.

packages.json
One Dark Theme + Dusk Theme = One Dark Colors with Dusk idea of a distinguished color for custom code
=> One Dusk Theme by Nuno Vieira

packages.json
Changed the name, and the description was wrong. Its more clear now.
=> One Dusk - Updated title and description

packages.json
Added a new "California" colour theme.
=> Added "California" theme.

packages.json
HKSnippet is a xcode plug-in for creating code snippet with triggers strings.
See detail from : https://github.com/hunk3000/HKSnippet
=> Add Xcode-Plugin HKSnippet

packages.json
=> Added AMAppExportToIPA

packages.json
Simulator build specs added in packages.json file
=> Simulator build specs added in packages.json

packages.json
=> LogDisabler

packages.json
A Xcode plugin to convert dictionary console output to NSDictionary literal
=> add EDSJSONToDictionary

packages.json
Linked to a broken site outside of github and I couldn't find an alternative.
=> removed screenshot for xTransCodelation.

packages.json
=> Add RAConsoleEditor plugin

packages.json
=> Add balckteatheme

packages.json
=> add GoOutside plugin

packages.json
=> RainyCode plugin

packages.json
I found the previously existing xTransCodelation, should not be added, but directly modify the line?
Sorry, too much trouble.Thanks.
=> Add a valid screenshot

packages.json
Add XSourceNote. Write notes when browsing source code , and generate a markdown article.
Repo : https://github.com/everettjf/XSourceNote
Thanks.
=> Add XSourceNote

packages.json
https://github.com/ML-Works/AnyFormat-Xcode
=> Added AnyFormat-Xcode

packages.json
refactor some method style, such as setter
=> add Refactor Code plugin

packages.json
InstaSwift an Xcode plugin allowing you to convert Objective-C code snippets into Swift instantly.
=> Add InstaSwift Xcode Plugin.

packages.json
We will fix some issues before a final release.
Thanks.
=> Remove InstaSwift xcode plugin.

packages.json
This plug-in provides "format on save" feature for swift file!
https://github.com/ypresto/SwiftLintXcode
=> Add SwiftLintXcode plugin

packages.json
Also clarifies the difference between "Snapshots" as is
=> Adds Snapshot Peek

packages.json
Add SQLPlugin plugin to Alcatraz
=> Add SQLPlugin plugin

packages.json
Update screenshot url for SQLPlugin. Sorry to make a mistake.
=> update screenshot URL

packages.json
I write a json text format plug for Xcode.
=> add JsonFormatter config

packages.json
LFAutoTarget is a plugin for Xcode which can help you select target automaticly when you add a new file. You can setup any target on the setting view.
Thanks
=> Add-LFAutoTarget-Xcode-plugin

packages.json
I’m serving 1gb a day with the old one!
=> Trim down Package Manager image

packages.json
Hi, I'm sorry but the package name I submitted wasn't match the Xcode project file
Thanks
=> Fix package name, remove space and exclamatory char

packages.json
- A dark side theme using flat colors
=> Add DarkSide theme

packages.json
- An Xcode plugin that makes working with color easier. Inspired by ColorSense-for-Xcode with extra care for Hex color
=> Add XcodeColorSense

packages.json
This move to the XVimProject organization is described in the project's readme.
=> Use updated XVim repository

packages.json
Add plugin ESTraslate to Alcatraz.
helps you translation of Xcode words quickly.
repo: [https://github.com/EnjoySR/ESTranslate-Xcode](https://github.com/EnjoySR/ESTranslate-Xcode)
Thanks!
=> Add plugin ESTraslate to Alcatraz

packages.json
Add Newzik templates for UIViewController and NSObject
=> Add Newzik Templates

packages.json
Lokaligo is no longer maintained and will stop working.
=> Remove Lokaligo plugin.

packages.json
XCode插件---shift + alt + t 翻译当前选中内容
=> Add Translate Plugin

packages.json
=> Add "HCTemplet" plugin

packages.json
=> add LCJSONFormatter plugin

packages.json
I've put it under the wrong category, sorry!
=> It's a Packages instead of Template.

packages.json
=> Add XXAlignOnSave

packages.json
I add a new Xcode plugin which helps people generate JsonModel Mapper automatically.
=> Add a new Xcode plugin.

packages.json
=> submit ProjectCleaner

packages.json
Plug-in for browsing Stackoverflow website inside XCode IDE.
=> Add FindIt Plug-In

packages.json
=> add OCProperty Transfer

packages.json
- AVBushwhacked
- AVTaintedPaint
- AVUnderwater
Remove Multiplex re: https://github.com/kolinkrewinkel/Multiplex/issues/40
=> Add Xcode themes

packages.json
=> add KWCodeLibrary

packages.json
The plugin intends to auto select targets depending of the selected configuration when you add files to the project.
Thanks
=> Add Auto Select Targets plugin

packages.json
You can connect to xcBuddy app and operate it with XcodeBuddy Plugin.
=> add XcodeBuddy plugin

packages.json
XcodeBuddyPlugin,change plugin name from XcodeBuddy to XcodeBuddyPlugin.
Thanks :)
=> change plugin name from XcodeBuddy to XcodeBuddyPlugin

packages.json
Re-indent everything, beautify JSON, etc.
No content has been altered. `git diff --ignore-all-space` yields:
```diff
diff --git a/packages.json b/packages.json
index f3d101d..591e2f7 100755
--- a/packages.json
+++ b/packages.json
@@ -72,7 +72,8 @@
"url": "https://github.com/poborp/XcodeFolders",
"description": "Extra menu for rapid folders.",
"screenshot": "https://raw.githubusercontent.com/poborp/XcodeFolders/master/Preview.png"
-    },    {
+      },
+      {
"name": "ESCodeSection",
"url": "https://github.com/ElfSundae/ESCodeSection",
"description": "Insert code separators."
@@ -2311,7 +2312,8 @@
"url": "https://raw.githubusercontent.com/sailorhg/fairyfloss/gh-pages/Fairyfloss.dvtcolortheme",
"description": "A pastel/candy/daydream fairyfloss theme by @sailorhg.",
"screenshot": …
```
=> Fix JSON formatting

packages.json
Plugin for Xcode to integrate the Reveal and Spark Inspector to your project automatic.
=> add DXViewInspectorPlugin
